/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ganesh.snpaas.hp.training.i12;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
